export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
  git
  jump
  docker
)

source $ZSH/oh-my-zsh.sh

# User configuration

export EDITOR=vim
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:/Users/jesperlugner/Documents/code/scripts/bin"
export AWS_VAULT_KEYCHAIN_NAME=login
export HOMEBREW_NO_ANALYTICS=1

eval "$(rbenv init - zsh)"

alias reload=". ~/.zshrc"
alias j="jump"
alias zconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias hammerconfig="code ~/.hammerspoon/init.lua"
alias cpwd="pwd | pbcopy"
alias releasediff='git log master..dev --merges --first-parent dev --pretty=format:"%h %<(10,trunc)%aN %C(white)%<(15)%ar%Creset %C(red bold)%<(15)%D%Creset %s"'
alias be='bundle exec'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
eval "$(pyenv init -)"
